name: "Test board"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  board-test:
    uses: catie-aq/zephyr_workflows/.github/workflows/board.yml@main
    with:
      board: "zest_core_stm32l562ve"

    secrets:
      personal_access_token: ${{ secrets.CI_6TRON_ZEPHYR_RO }}
